# Generated by Django 5.0.6 on 2024-06-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='imagen_default.png', upload_to='productos', verbose_name='Imagen'),
        ),
    ]
